// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, phone, password, avatar_url, bio, birthday
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING
  id, username, phone, password, avatar_url, bio, birthday,
  created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username  string
	Phone     string
	Password  string
	AvatarUrl string
	Bio       string
	Birthday  pgtype.Date
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Phone,
		arg.Password,
		arg.AvatarUrl,
		arg.Bio,
		arg.Birthday,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users SET
  deleted_at = now(),
  updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const detailUser = `-- name: DetailUser :one
SELECT
  id, username, phone, password, avatar_url, bio, birthday,
  created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DetailUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, detailUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT
  id, username, phone, password, avatar_url, bio, birthday,
  created_at, updated_at, deleted_at
FROM users
WHERE phone = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT
  id, username, phone, avatar_url, bio, birthday,
  created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32
	Offset int32
}

type GetUsersRow struct {
	ID        pgtype.UUID
	Username  string
	Phone     string
	AvatarUrl string
	Bio       string
	Birthday  pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Phone,
			&i.AvatarUrl,
			&i.Bio,
			&i.Birthday,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertUserRoleParams struct {
	UserID pgtype.UUID
	RoleID pgtype.UUID
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertUserRole, arg.UserID, arg.RoleID)
	return err
}

const listPermissionNamesForUser = `-- name: ListPermissionNamesForUser :many
SELECT DISTINCT p.name
FROM permissions p
INNER JOIN role_permissions rp ON rp.permission_id = p.id
INNER JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1 AND p.deleted_at IS NULL
ORDER BY p.name
`

func (q *Queries) ListPermissionNamesForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionNamesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleNamesForUser = `-- name: ListRoleNamesForUser :many
SELECT r.name
FROM roles r
INNER JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1 AND r.deleted_at IS NULL
ORDER BY r.name
`

func (q *Queries) ListRoleNamesForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleNamesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
  id, username, phone, password, avatar_url, bio, birthday,
  created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Phone,
			&i.Password,
			&i.AvatarUrl,
			&i.Bio,
			&i.Birthday,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  username = $2, phone = $3, password = $4, avatar_url = $5, bio = $6, birthday = $7
WHERE id = $1 AND deleted_at IS NULL RETURNING id, username, phone, password, avatar_url, bio, birthday, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID        pgtype.UUID
	Username  string
	Phone     string
	Password  string
	AvatarUrl string
	Bio       string
	Birthday  pgtype.Date
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Phone,
		arg.Password,
		arg.AvatarUrl,
		arg.Bio,
		arg.Birthday,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Password,
		&i.AvatarUrl,
		&i.Bio,
		&i.Birthday,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
