// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Role struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Phone     string
	Password  string
	AvatarUrl string
	Bio       string
	Birthday  pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type UserRole struct {
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
