// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachPermissionToRole = `-- name: AttachPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id) VALUES ($1, $2)
`

type AttachPermissionToRoleParams struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

func (q *Queries) AttachPermissionToRole(ctx context.Context, arg AttachPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, attachPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const detachPermissionFromRole = `-- name: DetachPermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type DetachPermissionFromRoleParams struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

func (q *Queries) DetachPermissionFromRole(ctx context.Context, arg DetachPermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, detachPermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT
  p.id, p.name, p.created_at, p.updated_at, p.deleted_at
FROM permissions p
INNER JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1 AND p.deleted_at IS NULL
ORDER BY p.name ASC
`

func (q *Queries) ListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
